### ISSUE TITLE
Add ability to use shortened commands

### ISSUE THREAD

**Issue by saloniamatteo** [bradford-smith94/informant#14]
Hello there!

Is it possible to add the option to use shortened commands? For example:

- instead of running `informant check`, run `informant c`;
- instead of running `informant list`, run `informant l`;
- instead of running `informant read 0`, run `informant r 0`

**Comment by x3a** [comment]
My humble opinion: You could set up aliases for that in the shell of your choice, I don't see any benefit in adding these shortcuts directly to informant itself.

**Comment by saloniamatteo** [comment]
> My humble opinion: You could set up aliases for that in the shell of your choice, I don't see any benefit in adding these shortcuts directly to informant itself.

How could I do this?

**Comment by x3a** [comment]
This is not a support forum for Linux questions and a generic answer to your question is impossible since it relies on the shell you are using, but consulting the documentation of your shell might give you a good starting point.

**Comment by saloniamatteo** [comment]
> This is not a support forum for Linux questions and a generic answer to your question is impossible since it relies on the shell you are using, but consulting the documentation of your shell might give you a good starting point.

What shell do you use? Could you provide me an example of how you'd do it on your shell?

**Comment by bradford-smith94** [comment]
When I started this project I chose to use `docopt` for argument parsing for it's simplicity (write good docstrings and you don't need any parser code), unless I'm reading the [documentation](http://docopt.org/) wrong `docopt` doesn't have this ability. So to achieve this, a new argument parser would need to used (I'm not really interested in doing that).

As mentioned you could achieve this in your own shell config. Aliases in bash or bash-like shells usually look something like `alias shortcommand="longercommand --other --options"` and are put in a file like `~/.bashrc` or `~/.bash_aliases` (all depending on shell and shell config of course). I don't think aliases like spaces in them, so what you actually may be after is defining a custom function in your shell to wrap `informant`.

In a bash-like shell this would look something like:
```
function informant () {
    # check $1 for 'c' or 'l' etc...
    /usr/bin/informant check
}
```
