### ISSUE TITLE
Wiishlist : Is it possible to give it a similar but different source to read the news

### ISSUE THREAD

**Issue by arcolinuxz** [bradford-smith94/informant#24]
I suppose it is now reading the webpage from Arch Linux News.

What if we add a config to it that provides an URL?

Can it be adapted to read that too?

**Comment by bradford-smith94** [comment]
Definitely, I was also thinking about this myself a little while ago (one of my machines runs Archlinux32 and it seems that project has it's own news feed).

In theory it should be able to do any RSS feed, whether or not the pacman hook still makes sense with other feeds is a different question. There's already a variable in the script that holds the URL for the news so it should be fairly easy to implement this.

**Comment by arcolinuxz** [comment]
sounds promising
Contact me again if you need a tester
