### ISSUE TITLE
Does this work with AUR helpers?

### ISSUE THREAD

**Issue by nigelwarning** [bradford-smith94/informant#27]
When updating AUR stuff I use the command Yay most of the time.

Does this work too with a AUR helper like yay?

**Comment by bradford-smith94** [comment]
It should. I don't know about yay specifically, but as far as I know most (all?) AUR helpers still rely on pacman (or at least makepkg, which uses pacman) to install packages.

I use auracle myself to download AUR packages and call makepkg manually to build and install them, and informant still gets called.

**Comment by nigelwarning** [comment]
Okay thanks!
