### ISSUE TITLE
Q regarding today's update

### ISSUE THREAD

**Issue by Strykar** [bradford-smith94/informant#3]
`pacman -Syu` fails today due to https://www.archlinux.org/news/xorg-cleanup-requires-manual-intervention/
It fails before `informant` can tell me to read the news, I'm wondering if this is a one-off case where updating fails before the pre-transaction hook?

**Comment by bradford-smith94** [comment]
Yeah, this failure occurs during dependency checking, which takes place before PreTransaction hooks are run. So unfortunately there is nothing `informant` can do to warn you about this case.

**Comment by Strykar** [comment]
Thanks for clearing that up.
