### ISSUE TITLE
Computer froze during pacman install, informant now hangs infinitely

### ISSUE THREAD

**Issue by brendenhoffman** [bradford-smith94/informant#37]
I was in the middle of fixing one of my AUR packages, I ran makepkg -si and my pc froze sometime after the pre transaction hooks. Informant is causing some unexpected behavior since it now hangs forever during any operation even with sudo. This is all I can get out of it now. Network does not seem to matter, but it does fail when no network is present.
```
$ sudo informant -d check
Getting datfile from "/var/lib/informant.dat"
cfg_fname: None
config: {}
cli args: {'--all': False,
 '--config': None,
 '--debug': True,
 '--file': None,
 '--help': False,
 '--no-cache': False,
 '--raw': False,
 '--reverse': False,
 '--unread': False,
 '--version': False,
 '<item>': None,
 'check': True,
 'list': False,
 'read': False}
```

Removing /var/lib/informant.dat or reinstalling does nothing.

**Comment by bradford-smith94** [comment]
You can try removing everything in `/var/cache/informant/` (`rm -r /var/cache/informant/*` - if you remove the informant directory there might be issues saving the cache, the program doesn't re-create the directory itself, I do that at install time).

If removing the cache files doesn't work I would suggest double checking your re-install. If a package version hasn't changed and you have a cached one already built in your system then makepkg will just re-install the cached one (a message gets printed about reinstalling from cache or something along those lines when this happens). You can do a full re-install by making sure to remove the cached package (probably in `/var/cache/pacman/pkg/informant-0.4.3-1-any.pkg.tar.zst` unless you've changed the location) before reinstalling informant.

If you've reinstalled and you know you aren't using a cached version, then I would double check the packages that informant depends on (`pacman -Qi informant` will list them), it might be that one of those packages needs to be re-installed.

**Comment by brendenhoffman** [comment]
I think deleting `/var/cache/informant/` did the trick. I actually didn't know the directory existed, I don't recall pacman ever listing that informant owned files there, so I didn't look.
I think it would be helpful if informant had a reset option. Afik clearing out that dir would do nothing harmful and its not hard to just read all the news again. I'm not sure though. Is there something stopping you or any risks there?

**Comment by bradford-smith94** [comment]
Sorry for not responding for so long, I don't think there are any risks or blockers here, just my time in getting around to it. I want to make some time to spend on informant tomorrow and this shouldn't be too hard to address.
