### ISSUE TITLE
Improve informant read

### ISSUE THREAD

**Issue by Strykar** [bradford-smith94/informant#5]
Couldn't `informant read` just have to be run once, and we hit `Space` or a key to confirm reading each of the 10 news post's instead of something like `for run in {1..10}; do informant; done`?

**Comment by ghost** [comment]
This pull request is relevant to your interests. https://github.com/bradford-smith94/informant/pull/7

**Comment by bradford-smith94** [comment]
An interactive mode is a nice idea. It would allow for actually reading all news items in a nice way while simplifying the commands you need to run.

The `--all` option as in #7 still has a place though for when the user has already read the news and just needs to mark them as read.

I think I would like both options.

**Comment by bradford-smith94** [comment]
This is done as of AUR version `0.2.0-1`.
